export const FETCH_KEYSTATS_SUCCESS = "FETCH_KEYSTATS_SUCCESS";
export type FETCH_KEYSTATS_SUCCESS = typeof FETCH_KEYSTATS_SUCCESS;

export const FETCH_KEYSTATS_FAILED = "FETCH_KEYSTATS_FAILED";
export type FETCH_KEYSTATS_FAILED = typeof FETCH_KEYSTATS_FAILED;