export const FETCH_PEER_SUCCESS = "FETCH_PEER_SUCCESS";
export type FETCH_PEER_SUCCESS = typeof FETCH_PEER_SUCCESS;

export const FETCH_PEER_FAILED = "FETCH_PEER_FAILED";
export type FETCH_PEER_FAILED = typeof FETCH_PEER_FAILED;