export const FETCH_OVERVIEW_SUCCESS = "FETCH_OVERVIEW_SUCCESS";
export type FETCH_OVERVIEW_SUCCESS = typeof FETCH_OVERVIEW_SUCCESS;

export const FETCH_OVERVIEW_FAILED = "FETCH_OVERVIEW_FAILED";
export type FETCH_OVERVIEW_FAILED = typeof FETCH_OVERVIEW_FAILED;