export const FETCH_MARKET_SUCCESS = "FETCH_MARKET_SUCCESS";
export type FETCH_MARKET_SUCCESS = typeof FETCH_MARKET_SUCCESS;

export const FETCH_MARKET_FAILED = "FETCH_MARKET_FAILED";
export type FETCH_MARKET_FAILED = typeof FETCH_MARKET_FAILED;
