export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export type FETCH_NEWS_SUCCESS = typeof FETCH_NEWS_SUCCESS;

export const FETCH_NEWS_FAILED = "FETCH_NEWS_FAILED";
export type FETCH_NEWS_FAILED = typeof FETCH_NEWS_FAILED;